- hosts: all
  sudo: yes
  tasks:
    - name: update yum to latest
      yum: name=* state=latest
    - name: install necessary packages
      yum: name={{item}}
      with_items:
        - epel-release
        - git
        - patch
        - libselinux-python
        - "@Development tools"
        - zlib-devel
        - bzip2-devel
        - openssl-devel
        - ncurses-devel
        - sqlite-devel
        - readline-devel
        - tk-devel
        - gcc-c++
        - glibc-headers

    # SELinux
    - selinux: state=disabled

    # memcached
    - yum: name=memcached
    - copy: src=files/etc/sysconfig/memcached dest=/etc/sysconfig/
    - service: name=memcached enabled=yes state=started

    # httpd
    - yum: name=httpd
    - yum: name=php
    - yum: name=php-mysql
    - yum: name=php-pecl-memcached
    - yum: name=php-pecl-igbinary
    - yum: name=php-xml
    - copy: src=files/etc/httpd/conf.d/isucon.conf dest=/etc/httpd/conf.d/
    - service: name=httpd enabled=yes state=started

    # user isucon
    - user: name=isucon
    - copy: src=files/home/isucon/env.sh dest=/home/isucon/ owner=isucon group=isucon mode=a+x
    - copy: src=files/etc/sudoers.d/isucon dest=/etc/sudoers.d/

    - git: repo=https://github.com/kayac/isucon3.git dest=/tmp/isucon3
    - shell: |
        set -e
        rsync -a /tmp/isucon3/qualifier/ /home/isucon/
        chown -R isucon:isucon /home/isucon/

    # mysql
    - yum: name=http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm
    - yum: name=mysql-community-server
    - yum: name=mysql-community-devel
    - yum: name=mysql-community-embedded
    - service: name=mysqld enabled=yes state=started
    - file: path=/opt/isucon/bin state=directory owner=isucon
    - file: path=/opt/isucon/data state=directory owner=isucon
    - copy: src=files/opt/isucon/data/init.sql.gz dest=/opt/isucon/data/
    - shell: |
        set -e
        ( echo ; echo Y ; echo root ; echo root ; echo Y ; echo Y ; echo Y ; echo Y ) | mysql_secure_installation
        mysqladmin -proot create isucon
        mysqladmin -proot create test
        echo "GRANT ALL ON isucon.* TO isucon@'%'" | mysql -proot
        gzip -dc /opt/isucon/data/init.sql.gz | mysql -proot isucon
        cat /usr/share/mysql/innodb_memcached_config.sql | mysql -proot
        echo "install plugin daemon_memcached soname \"libmemcached.so\"" | mysql -proot
        echo "[mysqld]" > /usr/my.cnf
      args:
        creates: /usr/my.cnf
      notify: restart mysqld
    - file: path=/etc/my.cnf state=absent

    # xbuild
    - yum: name=gcc
    - sudo_user: isucon
      git: repo=https://github.com/tagomoris/xbuild.git dest=/home/isucon/.xbuild

#---- ruby
    - name: install ruby2.3
      sudo_user: isucon
      shell: .xbuild/ruby-install 2.3.5 /home/isucon/.local/ruby-2.3
      args:
        creates: /home/isucon/.local/ruby-2.3/bin/ruby
    - name: copy Gemfile
      copy:
        src: 'files/home/isucon/webapp/ruby/Gemfile'
        dest: '/home/isucon/webapp/ruby/Gemfile'
    - name: copy Gemfile.lock
      copy:
        src: 'files/home/isucon/webapp/ruby/Gemfile.lock'
        dest: '/home/isucon/webapp/ruby/Gemfile.lock'
    - name: bundle install
      sudo_user: isucon
      shell: |
        set -e
        source ~/env.sh
        cd webapp/ruby/
        gem install bundler foreman
        bundle install --deployment --without development

#---- python3
    - become_user: isucon
      shell: .xbuild/python-install 3.3.2 /home/isucon/.local/python3
      args:
        chdir: /home/isucon/
        creates: /home/isucon/.local/python3/bin/python
    - become_user: isucon
      shell: |
        set -e
        source ./env.sh
        cd webapp/python/
        pip3 install --upgrade flask gunicorn python3-memcached PyMySQL==0.8.0 Werkzeug==0.14.1 click==6.7 itsdangerous==0.24 MarkupSafe==1.0
      args:
        chdir: /home/isucon/

    # bench
    - name: install golang
      become_user: isucon
      shell: .xbuild/go-install 1.9 /home/isucon/.local/go
      args:
        chdir: /home/isucon/
        creates: /home/isucon/.local/go/bin/go

    - yum: name=pigz
    - yum: name=libxml2-devel
    - sudo_user: isucon
      shell: |
        set -e
        source ~/env.sh
        cd qualifier_bench
        go get github.com/wsxiaoys/terminal/color
        go get github.com/moovweb/gokogiri/html
        go get github.com/moovweb/gokogiri
        go build

    # # supervisor package is too old
    # # - yum: name=supervisor
    # - yum: name=python-setuptools
    # - easy_install: name=supervisor
    # - copy: src=files/etc/init.d/supervisord dest=/etc/init.d/ mode=a+x
    # - copy: src=files/etc/sysconfig/supervisord dest=/etc/sysconfig/
    # - copy: src=files/etc/supervisord.conf dest=/etc/
    # - shell: /sbin/chkconfig --add supervisord
    # - service: name=supervisord enabled=yes state=started

    # cleanup
    - file: path=/home/isucon/.xbuild state=absent
    - file: path=/home/isucon/webapp/perl state=absent
    - file: path=/home/isucon/webapp/nodejs state=absent
    - file: path=/home/isucon/webapp/php state=absent
    - file: path=/tmp/isucon3 state=absent
    - file: path=/var/log/mysqld.log state=absent
    - file: path=/var/log/yum.log state=absent
    - shell: |
        rm -f /tmp/*-build*
        rm -f /tmp/python-*
        rm -f /tmp/isucon*
        rm -f /tmp/yum*

  handlers:
    - name: restart mysqld
      service: name=mysqld state=restarted
